### ISSUE TITLE
Setup install broken

### ISSUE THREAD

**Issue by 0xZDH** [0xZDH/o365spray#16]
When installing the tool via setuptools using: `python setup.py install` - the installation is broken via: `ModuleNotFoundError: No module named 'o365spray.core'`.

**Comment by 0xZDH** [comment]
Seems like the fix for this is to update the setup.cfg file under the `[options]` header. Currently, we are using the `find:` discovery method, but since we are importing as `o365spray.*` so it should instead be `find_namepsace:`

**Comment by tijldeneut** [comment]
Hi, great work with this program (and Omnispray). 
I still like o365spray because it has the validate option. 

With the current version in the master branch, I still have the error depicted in this thread. 
But I found a workaround to installing o365spray as a command within the path:
Tested on Debian 11 x64 with Python 3.9:

```
git clone https://github.com/0xZDH/o365spray && cd o365spray
python3 setup.py sdist && sudo pip3 install dist/o365spray-3.0.4.tar.gz
```

Maybe it could be an idea to put this on PyPi?

Thanks
